apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: etherpad-clusters
  namespace: etherpad
spec:
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
  clusterSelector:
    matchExpressions:
      - key: env_context
        operator: In
        values:
          - blue
          - green
