---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: pacman-app-latest
  namespace: pacman-app
  labels:
    name: pacman
spec:
  type: GitHub
  pathname: https://github.com/faizalak/k8s-pacman-app.git
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: pacman-app
  namespace: pacman-app
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
    - key: name
      operator: In
      values:
      - pacman
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/github-path: deploy
  name: pacman-app
  namespace: pacman-app
  labels:
    name: pacman
spec:
  channel: pacman-app/pacman-app-latest
  placement:
    placementRef:
      kind: PlacementRule
      name: pacman-dev-clusters
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: pacman-dev-clusters
  namespace: pacman-app
spec:
  clusterSelector:
    clusterReplicas: 1
    matchLabels:
      local-cluster: 'true'
    matchExpressions:
    - key: cloud
      operator: In
      values:
      - Amazon

